JointDict = {
    "Root": "root ground",

    "Thigh_L": "leg left thigh",
    "Thigh_R": "leg right thigh",
    "Knee_L": "leg left knee",
    "Knee_R": "leg right knee",
    "Foot_L": "leg left ankle",
    "Foot_R": "leg right ankle",

    "SpineLower": "spine lower",
    "SpineUpper": "spine upper",
    "Neck": "head neck lower",

    "Clavicle_L": "arm left shoulder 1",
    "Clavicle_R": "arm right shoulder 1",
    "Shoulder_L": "arm left shoulder 2",
    "Shoulder_R": "arm right shoulder 2",
    "Elbow_L": "arm left elbow",
    "Elbow_R": "arm right elbow",
    "Wrist_L": "arm left wrist",
    "Wrist_R": "arm right wrist",

    "Thumb_L1": "arm left finger 1a",
    "Thumb_L2": "arm left finger 1b",
    "Thumb_L3": "arm left finger 1c",
    "IndexFinger_L1": "arm left finger 2a",
    "IndexFinger_L2": "arm left finger 2b",
    "IndexFinger_L3": "arm left finger 2c",
    "MiddleFinger_L1": "arm left finger 3a",
    "MiddleFinger_L2": "arm left finger 3b",
    "MiddleFinger_L3": "arm left finger 3c",
    "RingFinger_L1": "arm left finger 4a",
    "RingFinger_L2": "arm left finger 4b",
    "RingFinger_L3": "arm left finger 4c",
    "LittleFinger_L1": "arm left finger 5a",
    "LittleFinger_L2": "arm left finger 5b",
    "LittleFinger_L3": "arm left finger 5c",

    "Thumb_R1": "arm right finger 1a",
    "Thumb_R2": "arm right finger 1b",
    "Thumb_R3": "arm right finger 1c",
    "IndexFinger_R1": "arm right finger 2a",
    "IndexFinger_R2": "arm right finger 2b",
    "IndexFinger_R3": "arm right finger 2c",
    "MiddleFinger_R1": "arm right finger 3a",
    "MiddleFinger_R2": "arm right finger 3b",
    "MiddleFinger_R3": "arm right finger 3c",
    "RingFinger_R1": "arm right finger 4a",
    "RingFinger_R2": "arm right finger 4b",
    "RingFinger_R3": "arm right finger 4c",
    "LittleFinger_R1": "arm right finger 5a",
    "LittleFinger_R2": "arm right finger 5b",
    "LittleFinger_R3": "arm right finger 5c",
}
