JointDict = {
    "Root": "ParentNode",
    
    "Thigh_L": "Leg_L",
    "Thigh_R": "Leg_R",
    "Knee_L": "Knee_L",
    "Knee_R": "Knee_R",
    "Foot_L": "Ankle_L",
    "Foot_R": "Ankle_R",

    "SpineLower": "UpperBody",
    "SpineUpper": "UpperBody2",
    "Neck": "Neck",

    "Clavicle_L": "ShoulderP_L",
    "Clavicle_R": "ShoulderP_R",
    "Shoulder_L": "Arm_L",
    "Shoulder_R": "Arm_R",
    "Elbow_L": "Elbow_L",
    "Elbow_R": "Elbow_R",
    "Wrist_L": "Wrist_L",
    "Wrist_R": "Wrist_R",

    "Thumb_L1": "Thumb0_L",
    "Thumb_L2": "Thumb1_L",
    "Thumb_L3": "Thumb2_L",
    "IndexFinger_L1": "IndexFinger1_L",
    "IndexFinger_L2": "IndexFinger2_L",
    "IndexFinger_L3": "IndexFinger3_L",
    "MiddleFinger_L1": "MiddleFinger1_L",
    "MiddleFinger_L2": "MiddleFinger2_L",
    "MiddleFinger_L3": "MiddleFinger3_L",
    "RingFinger_L1": "RingFinger1_L",
    "RingFinger_L2": "RingFinger2_L",
    "RingFinger_L3": "RingFinger3_L",
    "LittleFinger_L1": "LittleFinger1_L",
    "LittleFinger_L2": "LittleFinger2_L",
    "LittleFinger_L3": "LittleFinger3_L",

    "Thumb_R1": "Thumb0_R",
    "Thumb_R2": "Thumb1_R",
    "Thumb_R3": "Thumb2_R",
    "IndexFinger_R1": "IndexFinger1_R",
    "IndexFinger_R2": "IndexFinger2_R",
    "IndexFinger_R3": "IndexFinger3_R",
    "MiddleFinger_R1": "MiddleFinger1_R",
    "MiddleFinger_R2": "MiddleFinger2_R",
    "MiddleFinger_R3": "MiddleFinger3_R",
    "RingFinger_R1": "RingFinger1_R",
    "RingFinger_R2": "RingFinger2_R",
    "RingFinger_R3": "RingFinger3_R",
    "LittleFinger_R1": "LittleFinger1_R",
    "LittleFinger_R2": "LittleFinger2_R",
    "LittleFinger_R3": "LittleFinger3_R",
}
